### ISSUE TITLE
Fruit Quest Change

### ISSUE THREAD

**Issue by jsasasaaaaa** [RaftMechanic/Raft-Mechanic-Game-Mode#7]
Change the fruit quest for the trader to accept oranges and blueberries instead of bananas and blueberries, because the 2 banana crates are useless

**Comment by Tofix26** [comment]
Ok but why?

**Comment by jsasasaaaaa** [comment]
> Ok but why?

Because you need oranges and blueberries to get a spudgun that you need for the next quest

**Comment by Tofix26** [comment]
Alright then i guess we can change it
